### PR TITLE
Bump to 0.4.0 (no-read-only)

### PR DESCRIPTION
**Pull request by joshmoore**
Upgrades the image to use 0.4.0. There's a question of if we want this to be master/latest or if a `develop` is needed first to prevent conflicts. cc: @manics

### CODE REVIEW

**Comment by joshmoore** [comment]
Built & tested on beluga.

**Comment by manics** [comment]
Looks fine to me. Tagging/branching depends on what's happening with https://github.com/openmicroscopy/omero-server-docker/pull/1

**Comment by joshmoore** [comment]
This repo has no tags and ome's repo only has 0.1.0 so I'm not exactly sure. Perhaps longer term instead of using this repo we have IDR tags on the upstream on?

**Comment by manics** [comment]
Merge to master for now? What's relying on this Docker image?

**Comment by joshmoore** [comment]
There is the added complication that the other changes have been on `develop`, which I guess I could kill. Swarm has been using the `:develop` github tag, for example. Not sure if pyfeatures is dependent in any way.

**Comment by sbesson** [comment]
@joshmoore with the slow demise of `omero-grid-docker` in favor of `omero-server-docker` and `omero-web-docker`, I assume this is no longer needed/consumed anywhere?

**Comment by joshmoore** [comment]
Yeah. I haven't looked into omero-server and omero-web with IDR but I assume it would be quite straight-forward. Happy to ignore this.

**Pull request closed without merging**
